site_name: CiberBlog
site_url: https://github.com/Fildefrost

theme:
  name: material
  logo: assets/fs.png
  features:
    - navigation.tabs
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
  palette:
    - scheme: slate
      primary: black
      accent: blue
    - scheme: default
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Modo oscuro
  

plugins:
  - search
nav:
  - Inicio: index.md
  - Writeup-ctfs:
      - 📌 Info: Writeup-ctfs/info.md
      - 💻 BunkerLabs:
          - Document: Writeup-ctfs/BunkerLabs/Document.md
      - 💻 DockerLabs:
          - Agua de Mayo: Writeup-ctfs/DockerLabs/Agua de Mayo.md
          - Amor: Writeup-ctfs/DockerLabs/Amor.md
          - Chocolate: Writeup-ctfs/DockerLabs/Chocolate.md
          - Library: Writeup-ctfs/DockerLabs/Library.md
          - PN: Writeup-ctfs/DockerLabs/PN.md
          - ShowTime: Writeup-ctfs/DockerLabs/ShowTime.md
          - Trust: Writeup-ctfs/DockerLabs/Trust.md
          - Upload: Writeup-ctfs/DockerLabs/Upload.md
          - Walking CMS: Writeup-ctfs/DockerLabs/Walking CMS.md
          - WhereIsMyShell: Writeup-ctfs/DockerLabs/WhereIsMyShell.md
      - 💻 HackTheBox:
          - Archetype: Writeup-ctfs/HackTheBox/Archetype.md
          - Base: Writeup-ctfs/HackTheBox/Base.md
          - Bike: Writeup-ctfs/HackTheBox/Bike.md
          - Blocky: Writeup-ctfs/HackTheBox/Blocky.md
          - Blue: Writeup-ctfs/HackTheBox/Blue.md
          - BoardLight: Writeup-ctfs/HackTheBox/BoardLight.md
          - Cap: Writeup-ctfs/HackTheBox/Cap.md
          - Devel: Writeup-ctfs/HackTheBox/Devel.md
          - Explosion: Writeup-ctfs/HackTheBox/Explosion.md
          - Funnel: Writeup-ctfs/HackTheBox/Funnel.md
          - GoodGames: Writeup-ctfs/HackTheBox/GoodGames.md
          - Ignition: Writeup-ctfs/HackTheBox/Ignition.md
          - Included: Writeup-ctfs/HackTheBox/Included.md
          - Jerry: Writeup-ctfs/HackTheBox/Jerry.md
          - Keeper: Writeup-ctfs/HackTheBox/Keeper.md
          - Lame: Writeup-ctfs/HackTheBox/Lame.md
          - Markup: Writeup-ctfs/HackTheBox/Markup.md
          - Mongod: Writeup-ctfs/HackTheBox/Mongod.md
          - Oopsie: Writeup-ctfs/HackTheBox/Oopsie.md
          - Pennyworth: Writeup-ctfs/HackTheBox/Pennyworth.md
          - PermX: Writeup-ctfs/HackTheBox/PermX.md
          - Preignition: Writeup-ctfs/HackTheBox/Preignition.md
          - Sau: Writeup-ctfs/HackTheBox/Sau.md
          - Synced: Writeup-ctfs/HackTheBox/Synced.md
          - Tactics: Writeup-ctfs/HackTheBox/Tactics.md
          - Three: Writeup-ctfs/HackTheBox/Three.md
          - Unified: Writeup-ctfs/HackTheBox/Unified.md
          - Vaccine: Writeup-ctfs/HackTheBox/Vaccine.md
          - Validation: Writeup-ctfs/HackTheBox/Validation.md
      - 💻 TheHackerLabs:
         - BocataCalamares: Writeup-ctfs/TheHackerLabs/BocataCalamares.md
         - CanHackMe: Writeup-ctfs/TheHackerLabs/CanHackMe.md
         - CyberPunk: Writeup-ctfs/TheHackerLabs/CyberPunk.md 
      - 💻 Tryhackme:
          - Basic Pentesting: Writeup-ctfs/Tryhackme/Basic Pentesting.md
          - Capstone (Privesc): Writeup-ctfs/Tryhackme/Capstone (Privesc).md
          - ColdBox: Writeup-ctfs/Tryhackme/ColdBox.md
          - FownSniff: Writeup-ctfs/Tryhackme/FownSniff.md
          - Pickle Rick: Writeup-ctfs/Tryhackme/Pickle Rick.md
          - Root Me: Writeup-ctfs/Tryhackme/Root Me.md
          - Simple CTF: Writeup-ctfs/Tryhackme/Simple CTF.md
          - Steel Mountain: Writeup-ctfs/Tryhackme/Steel Mountain.md
  - Apuntes: 
      - Apuntes/info.md
      - Curso Python:
        - Cheatsheet:
          - Bolean Operators: Apuntes/CursoPython/CheatSheet/Bolean Operators.md
          - Data Types: Apuntes/CursoPython/CheatSheet/Data Types.md
          - Functions And Conditionals: Apuntes/CursoPython/CheatSheet/Functions and Conditionals.md
          - Loops: Apuntes/CursoPython/CheatSheet/Loops.md
          - Operations With Data Types: Apuntes/CursoPython/CheatSheet/Operations with Data Types.md
          - User Inputs: Apuntes/CursoPython/CheatSheet/User Inputs.md
        - Notas: Apuntes/CursoPython/python-course.md
      - eJPT:
        -  Apuntes/eJPT/MieJPTv2.md
        -  Apuntes/eJPT/WebPentesting.md
      - Sql: Apuntes/SQL/sql.md
  - Recursos: 
      - Recursos/info.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fildefrost
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jordi-ciber/

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/fildefrost"  target="_blank" rel="noopener">Fildefrost</a>